spring:
  application:
    name: batch-4-practice
  profiles:
    active: local

---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local

---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/batch_4_practice
      username: jinho
      password: jinho
      driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql
